version: '3'

services:
  backend:
    container_name: meapunto_backend
    image: backend:1
    build:
      context: ./App
      dockerfile: Dockerfile    

    environment:
      - ASPNETCORE_URLS=https://+:5001
    ports:
      - 5001:5001
    restart: always